<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Recliner</RootNamespace>
    <AssemblyName>RECLINER</AssemblyName>
    <AssemblyTitle>RECLINER</AssemblyTitle>
    <Product>RECLINER</Product>
    <Company>2300 Dynasty, LLC</Company>
    <Copyright>2300 Dynasty, LLC</Copyright>
    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <ApplicationIcon>Resources\recliner.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\recliner.ico" />
  </ItemGroup>
</Project>
